version: "3"

services:
  proxy:
    image: traefik:1.3.6-alpine
    volumes:
      - ./traefik/traefik.toml:/traefik.toml
    command: "--file"
    ports:
      - 8080:8080
      
  front:
    image: unqpdes/todo-list-front

  back:
    # build: "../2018-redux-todo-list-backend/"
    image: unqpdes/todo-list-back
    environment: 
      - MONGO_URL=mongodb://mongodb/pdes-todos

  mongodb:
    image: mongo
