defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":8080"

[frontends]
  [frontends.frontend1]
  backend = "backend1"
  
  [frontends.frontend2]
  backend = "backend2"
    [frontends.frontend2.routes.test_1]
      rule = "Path:/todos"
  
[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "http://front:3000"
  [backends.backend2]
    [backends.backend2.servers.server1]
    url = "http://back:3001"